name: TruffleHog Full History Scan (onboarding)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  trufflehog-full-history:
    name: trufflehog-full-history
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          fetch-depth: 0

      - name: TruffleHog OSS (full history)
        uses: trufflesecurity/trufflehog@2bffafb28044c57e14be4b02ef85c68a59dd5fab
        with:
          extra_args: --results=verified,unknown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
